os: linux-ppc64le

services:
  - docker

before_install:
  - docker pull registry.access.redhat.com/ubi8/ubi:latest
  
script:
  - mkdir out	
  - docker run -v `pwd`:/root/build --workdir=/root/build --name cockroachdb_ubi8 registry.access.redhat.com/ubi8/ubi:latest /bin/bash -c "bash cockroachdb_ubi8.sh"
  - docker cp cockroachdb_ubi8:/cockroachoss ./
  - docker stop cockroachdb_ubi8
  - docker rm cockroachdb_ubi8
  - chmod +x cockroach.sh
  - docker build  -t imamol555/cockroach:v19.2.10-ubi8 .

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: main
